#!/bin/sh
dir=`dirname "$0"`
cmd="$1"
if [ -z "$cmd" ]; then
	cmd="help"
else
	shift
	subcmd="$1"
	if [ -z "$subcmd" ]; then
		subcmd="help"
	else
		shift
	fi
	cmd="${cmd}_${subcmd}"
fi
arglist="[["
while [ $# -gt 0 ]; do
        next="$1"
        shift
        arglist="${arglist}\"${next}\""
        if [ $# -gt 0 ]; then
                arglist="${arglist},"
        fi
done
arglist="${arglist}]]"
# Force the start script to use nodetool instead of erl_call
# (since terminal redirection is broken in erl_call)
export USE_NODETOOL=1
exec $dir/rdpproxy rpc admin_cli "${cmd}" "${arglist}"
