#!/bin/sh
dir=`dirname "$0"`
cmd="$1"
if [ -z "$cmd" ]; then
	cmd="help"
else
	shift
	subcmd="$1"
	if [ -z "$subcmd" ]; then
		subcmd="help"
	else
		shift
	fi
	cmd="${cmd}_${subcmd}"
	if [ "$subcmd" == "update" ]; then
		arg="[$1"
		shift
		for x in "$@"; do
			arg="${arg},${x}"
		done
		arg="${arg}]."
		exec $dir/rdpproxy rpcterms admin_cli "${cmd}" "${arg}"
	fi
fi
exec $dir/rdpproxy rpc admin_cli "${cmd}" "$@"
