PKCS7 {iso(1) member-body(2) us(840) rsadsi(113549) pkcs(1) pkcs-7(7)
        modules(0) pkcs-7(1)}

DEFINITIONS EXPLICIT TAGS ::=
BEGIN

--
-- 3. Definitions
--

-- EXPORTS All;

--
-- 6. Useful types
--

-- Also defined in X.509
-- Redeclared here as a parameterized type
PKCS7AlgorithmIdentifier ::= SEQUENCE {
   algorithm   OBJECT IDENTIFIER,
   parameters  ANY DEFINED BY algorithm OPTIONAL
}

Data ::= OCTET STRING

DigestInfo ::= SEQUENCE {
  digestAlgorithm PKCS7AlgorithmIdentifier,
  digest          Digest
}

Digest ::= OCTET STRING

END
